CREATE USER appsis WITH PASSWORD 'Troca123';
GRANT ALL PRIVILEGES ON DATABASE investimentos TO appsis;
\connect investimentos;
GRANT USAGE, CREATE ON SCHEMA public TO appsis;
GRANT ALL ON SCHEMA public TO appsis;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO appsis;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO appsis;